[package]
name = "print-bindings"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "2"
env_logger = "0.7.0"
log = "0.4"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"

zoinks-lib = { path = "../zoinks-lib" }
